-- Users 
-- PROFILE
-- CATEGORY
-- PRODUCT
-- ORDER
CREATE TABLE users(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	fname VARCHAR(255) NOT NULL,
	lname VARCHAR(255) NOT NULL,
	password TEXT NOT NULL,
	user_name VARCHAR(320) UNIQUE NOT NULL
);
CREATE TABLE profiles(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	bio VARCHAR(512),
	avatar TEXT,
	is_verified BOOLEAN DEFAULT False,
	user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE categories(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE products(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	price NUMERIC(10,2) NOT NULL,
	description TEXT,
	category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT
);
CREATE TABLE orders(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	users_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE order_products(
 	product_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
	order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
	quantity INT NOT NULL
);